version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/maven-repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          key: Javafx-WebView-Debugger-repo
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run deploy
